Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/03/2023
Var

    a:inteiro
    b:inteiro
    c:inteiro


Inicio

     a <- 10
     b <- 20
     c <- a
     b <- c
     a <- b
     
     escreval("A: ",a)
     escreval("B: ",b)
     escreval("C: ",c)
     

Fimalgoritmo