Algoritmo "semnome"

Var

   a:inteiro
   b:inteiro
   c:inteiro


Inicio

      a <- 30
      b <- 20
      c <- a + b
      
       escreval("C: ",c)
       
       b <- 10
       
       escreval("B: ",b)
       escreval("C:",c)
       
       c <- a + b
       
       escreval("A: ",a)
       escreval("B: ",b)
       escreval("C: ",c)
       
       


Fimalgoritmo