Algoritmo "VOTO"

Var
 idade: inteiro

Inicio
escreval("Digite a sua idade: ")
leia(idade)
          SE ((idade >=18) e (idade<=65)) entao
            escreval("SEU VOTO É OBRIGATÓRIO")
          SENAO
          SE idade>65 entao
               escreval("SEU VOTO É OPCIONAL")
          SENAO
               escreval("SEU VOTO É OPCIONAL")
          FIMSE
          FIMSE


Fimalgoritmo