Algoritmo "áreadoRetângulo"

Var

   lado1:inteiro
   lado2:inteiro
   area:inteiro

Inicio

   escreval("Digite um número inteiro da base do retângulo:")
   leia(lado1)
   escreval("Digite um número inteiro da altura do retãngulo:")
   leia(lado2)
   
   area <- lado1 * lado2
   
   escreval("A área do seu retângulo com a base",lado1," e altura",lado2," é:",area)
   

Fimalgoritmo